language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
